-- 002_carga_traducciones.sql
-- Generado a partir de los Tag y claves de traducción utilizados por los formularios.
-- Puede ejecutarse más de una vez: actualiza las claves existentes e inserta las faltantes.

USE TP_Ing_De_Software;
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID(N'dbo.Idioma', N'U') IS NULL
        THROW 50001, N'No existe la tabla dbo.Idioma. Ejecute primero 001_creacion_base_datos.sql.', 1;

    IF OBJECT_ID(N'dbo.Traduccion', N'U') IS NULL
        THROW 50002, N'No existe la tabla dbo.Traduccion. Ejecute primero 001_creacion_base_datos.sql.', 1;

    IF NOT EXISTS (SELECT 1 FROM dbo.Idioma WHERE Codigo = N'es-AR')
        THROW 50003, N'No existe el idioma es-AR.', 1;

    IF NOT EXISTS (SELECT 1 FROM dbo.Idioma WHERE Codigo = N'en-US')
        THROW 50004, N'No existe el idioma en-US.', 1;

    DECLARE @Traducciones TABLE
    (
        CodigoIdioma nvarchar(10) NOT NULL,
        Clave nvarchar(200) NOT NULL,
        Texto nvarchar(500) NOT NULL,
        PRIMARY KEY (CodigoIdioma, Clave)
    );

    INSERT INTO @Traducciones (CodigoIdioma, Clave, Texto)
    VALUES
        (N'es-AR', N'Bitacora.Accion', N'Acción'),
        (N'en-US', N'Bitacora.Accion', N'Action'),
        (N'es-AR', N'Bitacora.Buscar', N'Buscar'),
        (N'en-US', N'Bitacora.Buscar', N'Search'),
        (N'es-AR', N'Bitacora.Cerrar', N'Cerrar'),
        (N'en-US', N'Bitacora.Cerrar', N'Close'),
        (N'es-AR', N'Bitacora.FechaDesde', N'Fecha desde'),
        (N'en-US', N'Bitacora.FechaDesde', N'Date from'),
        (N'es-AR', N'Bitacora.FechaHasta', N'Fecha hasta'),
        (N'en-US', N'Bitacora.FechaHasta', N'Date to'),
        (N'es-AR', N'Bitacora.Grilla.Accion', N'Acción'),
        (N'en-US', N'Bitacora.Grilla.Accion', N'Action'),
        (N'es-AR', N'Bitacora.Grilla.Descripcion', N'Descripción'),
        (N'en-US', N'Bitacora.Grilla.Descripcion', N'Description'),
        (N'es-AR', N'Bitacora.Grilla.Fecha', N'Fecha'),
        (N'en-US', N'Bitacora.Grilla.Fecha', N'Date'),
        (N'es-AR', N'Bitacora.Grilla.Modulo', N'Módulo'),
        (N'en-US', N'Bitacora.Grilla.Modulo', N'Module'),
        (N'es-AR', N'Bitacora.Grilla.Tipo', N'Tipo'),
        (N'en-US', N'Bitacora.Grilla.Tipo', N'Type'),
        (N'es-AR', N'Bitacora.Grilla.Usuario', N'Usuario'),
        (N'en-US', N'Bitacora.Grilla.Usuario', N'User'),
        (N'es-AR', N'Bitacora.Limpiar', N'Limpiar'),
        (N'en-US', N'Bitacora.Limpiar', N'Clear'),
        (N'es-AR', N'Bitacora.Modulo', N'Módulo'),
        (N'en-US', N'Bitacora.Modulo', N'Module'),
        (N'es-AR', N'Bitacora.Opciones.Idiomas', N'Idiomas'),
        (N'en-US', N'Bitacora.Opciones.Idiomas', N'Languages'),
        (N'es-AR', N'Bitacora.Opciones.Integridad', N'Integridad'),
        (N'en-US', N'Bitacora.Opciones.Integridad', N'Integrity'),
        (N'es-AR', N'Bitacora.Opciones.Permisos', N'Permisos'),
        (N'en-US', N'Bitacora.Opciones.Permisos', N'Permissions'),
        (N'es-AR', N'Bitacora.Opciones.Seguridad', N'Seguridad'),
        (N'en-US', N'Bitacora.Opciones.Seguridad', N'Security'),
        (N'es-AR', N'Bitacora.Opciones.Todos', N'Todos'),
        (N'en-US', N'Bitacora.Opciones.Todos', N'All'),
        (N'es-AR', N'Bitacora.Opciones.Traducciones', N'Traducciones'),
        (N'en-US', N'Bitacora.Opciones.Traducciones', N'Translations'),
        (N'es-AR', N'Bitacora.Opciones.Usuarios', N'Usuarios'),
        (N'en-US', N'Bitacora.Opciones.Usuarios', N'Users'),
        (N'es-AR', N'Bitacora.RegistrosEncontrados', N'Registros encontrados: {0}'),
        (N'en-US', N'Bitacora.RegistrosEncontrados', N'Records found: {0}'),
        (N'es-AR', N'Bitacora.Tipo', N'Tipo'),
        (N'en-US', N'Bitacora.Tipo', N'Type'),
        (N'es-AR', N'Bitacora.Titulo', N'Consulta de bitácora'),
        (N'en-US', N'Bitacora.Titulo', N'Audit log'),
        (N'es-AR', N'Bitacora.TituloVentana', N'Consulta de bitácora'),
        (N'en-US', N'Bitacora.TituloVentana', N'Audit log'),
        (N'es-AR', N'Bitacora.Usuario', N'Usuario'),
        (N'en-US', N'Bitacora.Usuario', N'User'),
        (N'es-AR', N'CambioPassword.Cancelar', N'Cancelar'),
        (N'en-US', N'CambioPassword.Cancelar', N'Cancel'),
        (N'es-AR', N'CambioPassword.Confirmar', N'Confirmar'),
        (N'en-US', N'CambioPassword.Confirmar', N'Confirm'),
        (N'es-AR', N'CambioPassword.ConfirmarPassword', N'Confirmar contraseña'),
        (N'en-US', N'CambioPassword.ConfirmarPassword', N'Confirm password'),
        (N'es-AR', N'CambioPassword.Descripcion', N'Usuario: {0}{1}Debe definir una nueva contraseña antes de continuar.'),
        (N'en-US', N'CambioPassword.Descripcion', N'User: {0}{1}You must set a new password before continuing.'),
        (N'es-AR', N'CambioPassword.NuevaPassword', N'Nueva contraseña'),
        (N'en-US', N'CambioPassword.NuevaPassword', N'New password'),
        (N'es-AR', N'CambioPassword.Titulo', N'Cambio obligatorio de contraseña'),
        (N'en-US', N'CambioPassword.Titulo', N'Mandatory password change'),
        (N'es-AR', N'CambioPassword.TituloVentana', N'Cambio obligatorio de contraseña'),
        (N'en-US', N'CambioPassword.TituloVentana', N'Mandatory password change'),
        (N'es-AR', N'General.Cerrar', N'Cerrar'),
        (N'en-US', N'General.Cerrar', N'Close'),
        (N'es-AR', N'General.Guardar', N'Guardar'),
        (N'en-US', N'General.Guardar', N'Save'),
        (N'es-AR', N'HistorialEmail.Cerrar', N'Cerrar'),
        (N'en-US', N'HistorialEmail.Cerrar', N'Close'),
        (N'es-AR', N'HistorialEmail.Grilla.EmailAnterior', N'Email anterior'),
        (N'en-US', N'HistorialEmail.Grilla.EmailAnterior', N'Previous email'),
        (N'es-AR', N'HistorialEmail.Grilla.EmailNuevo', N'Email nuevo'),
        (N'en-US', N'HistorialEmail.Grilla.EmailNuevo', N'New email'),
        (N'es-AR', N'HistorialEmail.Grilla.FechaCambio', N'Fecha cambio'),
        (N'en-US', N'HistorialEmail.Grilla.FechaCambio', N'Change date'),
        (N'es-AR', N'HistorialEmail.Grilla.UsuarioCambio', N'Usuario que cambió'),
        (N'en-US', N'HistorialEmail.Grilla.UsuarioCambio', N'Changed by'),
        (N'es-AR', N'HistorialEmail.RestaurarEmailSeleccionado', N'Restaurar email seleccionado'),
        (N'en-US', N'HistorialEmail.RestaurarEmailSeleccionado', N'Restore selected email'),
        (N'es-AR', N'HistorialEmail.Titulo', N'Historial de email'),
        (N'en-US', N'HistorialEmail.Titulo', N'Email history'),
        (N'es-AR', N'HistorialEmail.TituloVentana', N'Historial de email'),
        (N'en-US', N'HistorialEmail.TituloVentana', N'Email history'),
        (N'es-AR', N'Idiomas.Activar', N'Activar'),
        (N'en-US', N'Idiomas.Activar', N'Activate'),
        (N'es-AR', N'Idiomas.Activo', N'Activo'),
        (N'en-US', N'Idiomas.Activo', N'Active'),
        (N'es-AR', N'Idiomas.Cerrar', N'Cerrar'),
        (N'en-US', N'Idiomas.Cerrar', N'Close'),
        (N'es-AR', N'Idiomas.Codigo', N'Código'),
        (N'en-US', N'Idiomas.Codigo', N'Code'),
        (N'es-AR', N'Idiomas.Desactivar', N'Desactivar'),
        (N'en-US', N'Idiomas.Desactivar', N'Deactivate'),
        (N'es-AR', N'Idiomas.Grilla.Activo', N'Activo'),
        (N'en-US', N'Idiomas.Grilla.Activo', N'Active'),
        (N'es-AR', N'Idiomas.Grilla.Codigo', N'Código'),
        (N'en-US', N'Idiomas.Grilla.Codigo', N'Code'),
        (N'es-AR', N'Idiomas.Grilla.Nombre', N'Nombre'),
        (N'en-US', N'Idiomas.Grilla.Nombre', N'Name'),
        (N'es-AR', N'Idiomas.Guardar', N'Guardar'),
        (N'en-US', N'Idiomas.Guardar', N'Save'),
        (N'es-AR', N'Idiomas.Modificar', N'Modificar'),
        (N'en-US', N'Idiomas.Modificar', N'Edit'),
        (N'es-AR', N'Idiomas.Nombre', N'Nombre'),
        (N'en-US', N'Idiomas.Nombre', N'Name'),
        (N'es-AR', N'Idiomas.Nuevo', N'Nuevo'),
        (N'en-US', N'Idiomas.Nuevo', N'New'),
        (N'es-AR', N'Idiomas.TituloVentana', N'Gestión de idiomas'),
        (N'en-US', N'Idiomas.TituloVentana', N'Language management'),
        (N'es-AR', N'Login.Idioma', N'Idioma'),
        (N'en-US', N'Login.Idioma', N'Language'),
        (N'es-AR', N'Login.Ingresar', N'Ingresar'),
        (N'en-US', N'Login.Ingresar', N'Sign in'),
        (N'es-AR', N'Login.MensajeSeguridad', N'Acceso protegido.'),
        (N'en-US', N'Login.MensajeSeguridad', N'Protected access.'),
        (N'es-AR', N'Login.Password', N'Contraseña'),
        (N'en-US', N'Login.Password', N'Password'),
        (N'es-AR', N'Login.Subtitulo', N'Ingresá tus credenciales para acceder al sistema.'),
        (N'en-US', N'Login.Subtitulo', N'Enter your credentials to access the system.'),
        (N'es-AR', N'Login.Titulo', N'Iniciar sesión'),
        (N'en-US', N'Login.Titulo', N'Sign in'),
        (N'es-AR', N'Login.TituloVentana', N'Acceso al sistema'),
        (N'en-US', N'Login.TituloVentana', N'System access'),
        (N'es-AR', N'Login.Usuario', N'Usuario'),
        (N'en-US', N'Login.Usuario', N'Username'),
        (N'es-AR', N'Mensajes.Bitacora.ErrorConsulta', N'No se pudo consultar la bitácora. Verifique los filtros e intente nuevamente.'),
        (N'en-US', N'Mensajes.Bitacora.ErrorConsulta', N'The audit log could not be queried. Check the filters and try again.'),
        (N'es-AR', N'Mensajes.CambioPassword.ConfirmarPasswordRequerida', N'Debe confirmar la nueva contraseña.'),
        (N'en-US', N'Mensajes.CambioPassword.ConfirmarPasswordRequerida', N'You must confirm the new password.'),
        (N'es-AR', N'Mensajes.CambioPassword.ErrorCambio', N'No fue posible cambiar la contraseña. Verifique los datos e intente nuevamente.'),
        (N'en-US', N'Mensajes.CambioPassword.ErrorCambio', N'The password could not be changed. Check the data and try again.'),
        (N'es-AR', N'Mensajes.CambioPassword.NuevaPasswordRequerida', N'La nueva contraseña no puede estar vacía.'),
        (N'en-US', N'Mensajes.CambioPassword.NuevaPasswordRequerida', N'The new password cannot be empty.'),
        (N'es-AR', N'Mensajes.CambioPassword.PasswordActualizada', N'Contraseña actualizada correctamente.'),
        (N'en-US', N'Mensajes.CambioPassword.PasswordActualizada', N'Password updated successfully.'),
        (N'es-AR', N'Mensajes.CambioPassword.PasswordsNoCoinciden', N'La contraseña y su confirmación no coinciden.'),
        (N'en-US', N'Mensajes.CambioPassword.PasswordsNoCoinciden', N'The password and its confirmation do not match.'),
        (N'es-AR', N'Mensajes.HistorialEmail.ConfirmarRestaurar', N'¿Desea restaurar el email anterior del usuario ''{0}''?' + NCHAR(13) + NCHAR(10) + N'' + NCHAR(13) + NCHAR(10) + N'Email a restaurar: {1}'),
        (N'en-US', N'Mensajes.HistorialEmail.ConfirmarRestaurar', N'Do you want to restore the previous email for user ''{0}''?' + NCHAR(13) + NCHAR(10) + N'' + NCHAR(13) + NCHAR(10) + N'Email to restore: {1}'),
        (N'es-AR', N'Mensajes.HistorialEmail.EmailRestaurado', N'El email fue restaurado correctamente.'),
        (N'en-US', N'Mensajes.HistorialEmail.EmailRestaurado', N'The email was restored successfully.'),
        (N'es-AR', N'Mensajes.HistorialEmail.ErrorRestaurar', N'No fue posible restaurar el email. Verifique los datos e intente nuevamente.'),
        (N'en-US', N'Mensajes.HistorialEmail.ErrorRestaurar', N'The email could not be restored. Check the data and try again.'),
        (N'es-AR', N'Mensajes.HistorialEmail.SeleccionarRegistro', N'Debe seleccionar un registro del historial.'),
        (N'en-US', N'Mensajes.HistorialEmail.SeleccionarRegistro', N'You must select a history record.'),
        (N'es-AR', N'Mensajes.Idioma.ErrorCambio', N'No fue posible cambiar el idioma.'),
        (N'en-US', N'Mensajes.Idioma.ErrorCambio', N'The language could not be changed.'),
        (N'es-AR', N'Mensajes.Idioma.ErrorGuardarPreferencia', N'El idioma fue cambiado, pero no se pudo guardar como preferencia del usuario.'),
        (N'en-US', N'Mensajes.Idioma.ErrorGuardarPreferencia', N'The language was changed, but it could not be saved as the user''s preference.'),
        (N'es-AR', N'Mensajes.Idiomas.CodigoRequerido', N'Debe ingresar el código del idioma.'),
        (N'en-US', N'Mensajes.Idiomas.CodigoRequerido', N'You must enter the language code.'),
        (N'es-AR', N'Mensajes.Idiomas.ConfirmarActivar', N'¿Está seguro que desea activar el idioma seleccionado?'),
        (N'en-US', N'Mensajes.Idiomas.ConfirmarActivar', N'Are you sure you want to activate the selected language?'),
        (N'es-AR', N'Mensajes.Idiomas.ConfirmarDesactivar', N'¿Está seguro que desea desactivar el idioma seleccionado?'),
        (N'en-US', N'Mensajes.Idiomas.ConfirmarDesactivar', N'Are you sure you want to deactivate the selected language?'),
        (N'es-AR', N'Mensajes.Idiomas.DebeSeleccionarIdioma', N'Debe seleccionar un idioma.'),
        (N'en-US', N'Mensajes.Idiomas.DebeSeleccionarIdioma', N'You must select a language.'),
        (N'es-AR', N'Mensajes.Idiomas.ErrorCambiarEstado', N'No fue posible cambiar el estado del idioma. Verifique los datos e intente nuevamente.'),
        (N'en-US', N'Mensajes.Idiomas.ErrorCambiarEstado', N'The language status could not be changed. Check the data and try again.'),
        (N'es-AR', N'Mensajes.Idiomas.ErrorGuardar', N'No fue posible guardar el idioma. Verifique los datos e intente nuevamente.'),
        (N'en-US', N'Mensajes.Idiomas.ErrorGuardar', N'The language could not be saved. Check the data and try again.'),
        (N'es-AR', N'Mensajes.Idiomas.ErrorModificar', N'No fue posible modificar el idioma. Verifique los datos e intente nuevamente.'),
        (N'en-US', N'Mensajes.Idiomas.ErrorModificar', N'The language could not be updated. Check the data and try again.'),
        (N'es-AR', N'Mensajes.Idiomas.IdiomaActivado', N'Idioma activado correctamente.'),
        (N'en-US', N'Mensajes.Idiomas.IdiomaActivado', N'Language activated successfully.'),
        (N'es-AR', N'Mensajes.Idiomas.IdiomaDesactivado', N'Idioma desactivado correctamente.'),
        (N'en-US', N'Mensajes.Idiomas.IdiomaDesactivado', N'Language deactivated successfully.'),
        (N'es-AR', N'Mensajes.Idiomas.IdiomaGuardado', N'Idioma guardado correctamente.'),
        (N'en-US', N'Mensajes.Idiomas.IdiomaGuardado', N'Language saved successfully.'),
        (N'es-AR', N'Mensajes.Idiomas.IdiomaModificado', N'Idioma modificado correctamente.'),
        (N'en-US', N'Mensajes.Idiomas.IdiomaModificado', N'Language updated successfully.'),
        (N'es-AR', N'Mensajes.Idiomas.NombreRequerido', N'Debe ingresar el nombre del idioma.'),
        (N'en-US', N'Mensajes.Idiomas.NombreRequerido', N'You must enter the language name.'),
        (N'es-AR', N'Mensajes.Login.CredencialesInvalidas', N'Usuario o contraseña incorrectos.'),
        (N'en-US', N'Mensajes.Login.CredencialesInvalidas', N'Incorrect username or password.'),
        (N'es-AR', N'Mensajes.Login.ErrorConexion', N'No fue posible conectarse con la base de datos. Verifique la conexión e intente nuevamente.'),
        (N'en-US', N'Mensajes.Login.ErrorConexion', N'The database connection could not be established. Check the connection and try again.'),
        (N'es-AR', N'Mensajes.Login.ErrorVerificarIntegridad', N'No fue posible verificar la integridad de la base de datos. Verifique la conexión e intente nuevamente.'),
        (N'en-US', N'Mensajes.Login.ErrorVerificarIntegridad', N'The database integrity could not be verified. Check the connection and try again.'),
        (N'es-AR', N'Mensajes.Login.IntegridadVulneradaAdmin', N'Se detectó una falla de integridad en la base de datos.' + NCHAR(13) + NCHAR(10) + N'' + NCHAR(13) + NCHAR(10) + N'Ingresará como administrador para recalcular los dígitos verificadores y desbloquear usuarios.'),
        (N'en-US', N'Mensajes.Login.IntegridadVulneradaAdmin', N'A database integrity failure was detected.' + NCHAR(13) + NCHAR(10) + N'' + NCHAR(13) + NCHAR(10) + N'You will sign in as administrator to recalculate the verification digits and unblock users.'),
        (N'es-AR', N'Mensajes.Login.IntegridadVulneradaUsuario', N'Se detectó una falla de integridad en la base de datos. Por seguridad, solo el administrador puede ingresar para recalcular los dígitos verificadores.'),
        (N'en-US', N'Mensajes.Login.IntegridadVulneradaUsuario', N'A database integrity failure was detected. For security reasons, only the administrator can sign in to recalculate the verification digits.'),
        (N'es-AR', N'Mensajes.Login.PasswordRequerido', N'Por favor, ingrese su contraseña.'),
        (N'en-US', N'Mensajes.Login.PasswordRequerido', N'Please enter your password.'),
        (N'es-AR', N'Mensajes.Login.UsuarioBloqueado', N'El acceso fue bloqueado temporalmente por varios intentos fallidos. Intente nuevamente en unos minutos.'),
        (N'en-US', N'Mensajes.Login.UsuarioBloqueado', N'Access was temporarily blocked after several failed attempts. Try again in a few minutes.'),
        (N'es-AR', N'Mensajes.Login.UsuarioBloqueadoConMinutos', N'El acceso fue bloqueado temporalmente. Intente nuevamente en aproximadamente {0} minuto(s).'),
        (N'en-US', N'Mensajes.Login.UsuarioBloqueadoConMinutos', N'Access was temporarily blocked. Try again in approximately {0} minute(s).'),
        (N'es-AR', N'Mensajes.Login.UsuarioBloqueadoPorIntegridad', N'El usuario se encuentra bloqueado por una falla de integridad. Debe ingresar el administrador para recalcular los dígitos verificadores.'),
        (N'en-US', N'Mensajes.Login.UsuarioBloqueadoPorIntegridad', N'The user is blocked because of an integrity failure. The administrator must sign in to recalculate the verification digits.'),
        (N'es-AR', N'Mensajes.Login.UsuarioRequerido', N'Por favor, ingrese su nombre de usuario.'),
        (N'en-US', N'Mensajes.Login.UsuarioRequerido', N'Please enter your username.'),
        (N'es-AR', N'Mensajes.Principal.ConfirmarDesbloquearIntegridad', N'Esta acción desbloqueará a los usuarios que fueron bloqueados por falla de integridad.' + NCHAR(13) + NCHAR(10) + N'' + NCHAR(13) + NCHAR(10) + N'Se recomienda hacerlo después de recalcular los dígitos verificadores.' + NCHAR(13) + NCHAR(10) + N'' + NCHAR(13) + NCHAR(10) + N'¿Desea continuar?'),
        (N'en-US', N'Mensajes.Principal.ConfirmarDesbloquearIntegridad', N'This action will unblock users who were blocked because of an integrity failure.' + NCHAR(13) + NCHAR(10) + N'' + NCHAR(13) + NCHAR(10) + N'It is recommended to do this after recalculating the verification digits.' + NCHAR(13) + NCHAR(10) + N'' + NCHAR(13) + NCHAR(10) + N'Do you want to continue?'),
        (N'es-AR', N'Mensajes.Principal.ConfirmarRecalcularDigitos', N'Esta acción recalculará los dígitos verificadores de usuarios.' + NCHAR(13) + NCHAR(10) + N'' + NCHAR(13) + NCHAR(10) + N'Importante: el recálculo no restaura datos modificados por fuera del sistema, sino que toma el estado actual de la base como nuevo estado válido.' + NCHAR(13) + NCHAR(10) + N'' + NCHAR(13) + NCHAR(10) + N'¿Desea continuar?'),
        (N'en-US', N'Mensajes.Principal.ConfirmarRecalcularDigitos', N'This action will recalculate the user verification digits.' + NCHAR(13) + NCHAR(10) + N'' + NCHAR(13) + NCHAR(10) + N'Important: recalculation does not restore data modified outside the system; it takes the current database state as the new valid state.' + NCHAR(13) + NCHAR(10) + N'' + NCHAR(13) + NCHAR(10) + N'Do you want to continue?'),
        (N'es-AR', N'Mensajes.Principal.DesbloqueoIntegridadCorrecto', N'Los usuarios bloqueados por integridad fueron desbloqueados correctamente.'),
        (N'en-US', N'Mensajes.Principal.DesbloqueoIntegridadCorrecto', N'Users blocked by integrity checks were unblocked successfully.'),
        (N'es-AR', N'Mensajes.Principal.ErrorDesbloquearIntegridad', N'No fue posible desbloquear los usuarios por integridad. Verifique el estado de la base e intente nuevamente.'),
        (N'en-US', N'Mensajes.Principal.ErrorDesbloquearIntegridad', N'Users blocked by integrity checks could not be unblocked. Check the database status and try again.'),
        (N'es-AR', N'Mensajes.Principal.ErrorRecalcularDigitos', N'No fue posible recalcular los dígitos verificadores. Verifique el estado de la base e intente nuevamente.'),
        (N'en-US', N'Mensajes.Principal.ErrorRecalcularDigitos', N'The verification digits could not be recalculated. Check the database status and try again.'),
        (N'es-AR', N'Mensajes.Principal.RecalculoDigitosCorrecto', N'Los dígitos verificadores fueron recalculados correctamente.'),
        (N'en-US', N'Mensajes.Principal.RecalculoDigitosCorrecto', N'The verification digits were recalculated successfully.'),
        (N'es-AR', N'Mensajes.Titulos.AccesoBloqueado', N'Acceso bloqueado'),
        (N'en-US', N'Mensajes.Titulos.AccesoBloqueado', N'Access blocked'),
        (N'es-AR', N'Mensajes.Titulos.AccesoBloqueadoIntegridad', N'Acceso bloqueado por integridad'),
        (N'en-US', N'Mensajes.Titulos.AccesoBloqueadoIntegridad', N'Access blocked by integrity check'),
        (N'es-AR', N'Mensajes.Titulos.CambiarEstadoIdioma', N'Cambiar estado del idioma'),
        (N'en-US', N'Mensajes.Titulos.CambiarEstadoIdioma', N'Change language status'),
        (N'es-AR', N'Mensajes.Titulos.CambioPassword', N'Cambio de contraseña'),
        (N'en-US', N'Mensajes.Titulos.CambioPassword', N'Password change'),
        (N'es-AR', N'Mensajes.Titulos.ConfirmarBlanqueoPassword', N'Confirmar blanqueo de contraseña'),
        (N'en-US', N'Mensajes.Titulos.ConfirmarBlanqueoPassword', N'Confirm password reset'),
        (N'es-AR', N'Mensajes.Titulos.ConfirmarCambioEstado', N'Confirmar cambio de estado'),
        (N'en-US', N'Mensajes.Titulos.ConfirmarCambioEstado', N'Confirm status change'),
        (N'es-AR', N'Mensajes.Titulos.DesbloquearIntegridad', N'Desbloquear usuarios por integridad'),
        (N'en-US', N'Mensajes.Titulos.DesbloquearIntegridad', N'Unblock users after integrity failure'),
        (N'es-AR', N'Mensajes.Titulos.EdicionEnCurso', N'Edición en curso'),
        (N'en-US', N'Mensajes.Titulos.EdicionEnCurso', N'Edit in progress'),
        (N'es-AR', N'Mensajes.Titulos.EliminarTraduccion', N'Eliminar traducción'),
        (N'en-US', N'Mensajes.Titulos.EliminarTraduccion', N'Delete translation'),
        (N'es-AR', N'Mensajes.Titulos.Error', N'Error'),
        (N'en-US', N'Mensajes.Titulos.Error', N'Error'),
        (N'es-AR', N'Mensajes.Titulos.ErrorConexion', N'Error de conexión'),
        (N'en-US', N'Mensajes.Titulos.ErrorConexion', N'Connection error'),
        (N'es-AR', N'Mensajes.Titulos.ErrorConfiguracion', N'Error de configuración'),
        (N'en-US', N'Mensajes.Titulos.ErrorConfiguracion', N'Configuration error'),
        (N'es-AR', N'Mensajes.Titulos.ErrorIntegridad', N'Error de integridad'),
        (N'en-US', N'Mensajes.Titulos.ErrorIntegridad', N'Integrity error'),
        (N'es-AR', N'Mensajes.Titulos.GestionUsuarios', N'Gestión de usuarios'),
        (N'en-US', N'Mensajes.Titulos.GestionUsuarios', N'User management'),
        (N'es-AR', N'Mensajes.Titulos.HistorialEmail', N'Historial de email'),
        (N'en-US', N'Mensajes.Titulos.HistorialEmail', N'Email history'),
        (N'es-AR', N'Mensajes.Titulos.Idioma', N'Idioma'),
        (N'en-US', N'Mensajes.Titulos.Idioma', N'Language'),
        (N'es-AR', N'Mensajes.Titulos.Idiomas', N'Idiomas'),
        (N'en-US', N'Mensajes.Titulos.Idiomas', N'Languages'),
        (N'es-AR', N'Mensajes.Titulos.Integridad', N'Integridad'),
        (N'en-US', N'Mensajes.Titulos.Integridad', N'Integrity'),
        (N'es-AR', N'Mensajes.Titulos.IntegridadVulnerada', N'Integridad vulnerada'),
        (N'en-US', N'Mensajes.Titulos.IntegridadVulnerada', N'Integrity compromised'),
        (N'es-AR', N'Mensajes.Titulos.Login', N'Login'),
        (N'en-US', N'Mensajes.Titulos.Login', N'Login'),
        (N'es-AR', N'Mensajes.Titulos.NoPudoBlanquearPassword', N'No se pudo blanquear la contraseña'),
        (N'en-US', N'Mensajes.Titulos.NoPudoBlanquearPassword', N'The password could not be reset'),
        (N'es-AR', N'Mensajes.Titulos.NoPudoCambiarEstadoUsuario', N'No se pudo cambiar el estado del usuario'),
        (N'en-US', N'Mensajes.Titulos.NoPudoCambiarEstadoUsuario', N'The user status could not be changed'),
        (N'es-AR', N'Mensajes.Titulos.NoPudoCambiarPassword', N'No se pudo cambiar la contraseña'),
        (N'en-US', N'Mensajes.Titulos.NoPudoCambiarPassword', N'The password could not be changed'),
        (N'es-AR', N'Mensajes.Titulos.NoPudoConsultarBitacora', N'No se pudo consultar la bitácora'),
        (N'en-US', N'Mensajes.Titulos.NoPudoConsultarBitacora', N'The audit log could not be queried'),
        (N'es-AR', N'Mensajes.Titulos.NoPudoGuardarUsuario', N'No se pudo guardar el usuario'),
        (N'en-US', N'Mensajes.Titulos.NoPudoGuardarUsuario', N'The user could not be saved'),
        (N'es-AR', N'Mensajes.Titulos.OperacionNoDisponible', N'Operación no disponible'),
        (N'en-US', N'Mensajes.Titulos.OperacionNoDisponible', N'Operation unavailable'),
        (N'es-AR', N'Mensajes.Titulos.RecalcularDigitos', N'Recalcular dígitos verificadores'),
        (N'en-US', N'Mensajes.Titulos.RecalcularDigitos', N'Recalculate verification digits'),
        (N'es-AR', N'Mensajes.Titulos.RestaurarEmail', N'Restaurar email'),
        (N'en-US', N'Mensajes.Titulos.RestaurarEmail', N'Restore email'),
        (N'es-AR', N'Mensajes.Titulos.SinPermiso', N'Sin permiso'),
        (N'en-US', N'Mensajes.Titulos.SinPermiso', N'Permission denied'),
        (N'es-AR', N'Mensajes.Titulos.Traducciones', N'Traducciones'),
        (N'en-US', N'Mensajes.Titulos.Traducciones', N'Translations'),
        (N'es-AR', N'Mensajes.Titulos.UsuarioNoSeleccionado', N'Usuario no seleccionado'),
        (N'en-US', N'Mensajes.Titulos.UsuarioNoSeleccionado', N'No user selected'),
        (N'es-AR', N'Mensajes.Titulos.Validacion', N'Validación'),
        (N'en-US', N'Mensajes.Titulos.Validacion', N'Validation'),
        (N'es-AR', N'Mensajes.Traducciones.ClaveRequerida', N'Debe ingresar la clave de traducción.'),
        (N'en-US', N'Mensajes.Traducciones.ClaveRequerida', N'You must enter the translation key.'),
        (N'es-AR', N'Mensajes.Traducciones.ConfirmarEliminar', N'¿Está seguro que desea eliminar la traducción seleccionada?'),
        (N'en-US', N'Mensajes.Traducciones.ConfirmarEliminar', N'Are you sure you want to delete the selected translation?'),
        (N'es-AR', N'Mensajes.Traducciones.DebeSeleccionarIdioma', N'Debe seleccionar un idioma.'),
        (N'en-US', N'Mensajes.Traducciones.DebeSeleccionarIdioma', N'You must select a language.'),
        (N'es-AR', N'Mensajes.Traducciones.DebeSeleccionarTraduccion', N'Debe seleccionar una traducción.'),
        (N'en-US', N'Mensajes.Traducciones.DebeSeleccionarTraduccion', N'You must select a translation.'),
        (N'es-AR', N'Mensajes.Traducciones.ErrorEliminar', N'No fue posible eliminar la traducción. Verifique los datos e intente nuevamente.'),
        (N'en-US', N'Mensajes.Traducciones.ErrorEliminar', N'The translation could not be deleted. Check the data and try again.'),
        (N'es-AR', N'Mensajes.Traducciones.ErrorGuardar', N'No fue posible guardar la traducción. Verifique los datos e intente nuevamente.'),
        (N'en-US', N'Mensajes.Traducciones.ErrorGuardar', N'The translation could not be saved. Check the data and try again.'),
        (N'es-AR', N'Mensajes.Traducciones.ErrorModificar', N'No fue posible modificar la traducción. Verifique los datos e intente nuevamente.'),
        (N'en-US', N'Mensajes.Traducciones.ErrorModificar', N'The translation could not be updated. Check the data and try again.'),
        (N'es-AR', N'Mensajes.Traducciones.TextoRequerido', N'Debe ingresar el texto de la traducción.'),
        (N'en-US', N'Mensajes.Traducciones.TextoRequerido', N'You must enter the translation text.'),
        (N'es-AR', N'Mensajes.Traducciones.TraduccionEliminada', N'Traducción eliminada correctamente.'),
        (N'en-US', N'Mensajes.Traducciones.TraduccionEliminada', N'Translation deleted successfully.'),
        (N'es-AR', N'Mensajes.Traducciones.TraduccionGuardada', N'Traducción guardada correctamente.'),
        (N'en-US', N'Mensajes.Traducciones.TraduccionGuardada', N'Translation saved successfully.'),
        (N'es-AR', N'Mensajes.Traducciones.TraduccionModificada', N'Traducción modificada correctamente.'),
        (N'en-US', N'Mensajes.Traducciones.TraduccionModificada', N'Translation updated successfully.'),
        (N'es-AR', N'Mensajes.Usuarios.ConfirmarBlanquearPassword', N'¿Confirmás que querés blanquear la contraseña del usuario ''{0}''?'),
        (N'en-US', N'Mensajes.Usuarios.ConfirmarBlanquearPassword', N'Are you sure you want to reset the password for user ''{0}''?'),
        (N'es-AR', N'Mensajes.Usuarios.ConfirmarInhabilitar', N'¿Confirmás que querés inhabilitar el usuario ''{0}''?'),
        (N'en-US', N'Mensajes.Usuarios.ConfirmarInhabilitar', N'Are you sure you want to disable user ''{0}''?'),
        (N'es-AR', N'Mensajes.Usuarios.ConfirmarReactivar', N'¿Confirmás que querés reactivar el usuario ''{0}''?'),
        (N'en-US', N'Mensajes.Usuarios.ConfirmarReactivar', N'Are you sure you want to reactivate user ''{0}''?'),
        (N'es-AR', N'Mensajes.Usuarios.EdicionEnCursoCambioEstado', N'Terminá la edición actual guardando o cancelando antes de cambiar el estado del usuario.'),
        (N'en-US', N'Mensajes.Usuarios.EdicionEnCursoCambioEstado', N'Finish the current edit by saving or cancelling before changing the user''s status.'),
        (N'es-AR', N'Mensajes.Usuarios.EmailRequerido', N'El email no puede estar vacío.'),
        (N'en-US', N'Mensajes.Usuarios.EmailRequerido', N'The email cannot be empty.'),
        (N'es-AR', N'Mensajes.Usuarios.NombreCompletoRequerido', N'El nombre completo no puede estar vacío.'),
        (N'en-US', N'Mensajes.Usuarios.NombreCompletoRequerido', N'The full name cannot be empty.'),
        (N'es-AR', N'Mensajes.Usuarios.NombreUsuarioRequerido', N'El nombre de usuario no puede estar vacío.'),
        (N'en-US', N'Mensajes.Usuarios.NombreUsuarioRequerido', N'The username cannot be empty.'),
        (N'es-AR', N'Mensajes.Usuarios.OperacionGuardarNoDisponible', N'Seleccioná una operación válida antes de guardar.'),
        (N'en-US', N'Mensajes.Usuarios.OperacionGuardarNoDisponible', N'Select a valid operation before saving.'),
        (N'es-AR', N'Mensajes.Usuarios.PasswordBlanqueada', N'Contraseña blanqueada correctamente.' + NCHAR(13) + NCHAR(10) + N'' + NCHAR(13) + NCHAR(10) + N'Usuario: {0}' + NCHAR(13) + NCHAR(10) + N'Contraseña temporal: {1}' + NCHAR(13) + NCHAR(10) + N'' + NCHAR(13) + NCHAR(10) + N'Al ingresar, el usuario deberá cambiar su contraseña.'),
        (N'en-US', N'Mensajes.Usuarios.PasswordBlanqueada', N'Password reset successfully.' + NCHAR(13) + NCHAR(10) + N'' + NCHAR(13) + NCHAR(10) + N'User: {0}' + NCHAR(13) + NCHAR(10) + N'Temporary password: {1}' + NCHAR(13) + NCHAR(10) + N'' + NCHAR(13) + NCHAR(10) + N'The user must change the password at the next sign-in.'),
        (N'es-AR', N'Mensajes.Usuarios.PasswordRequerida', N'La contraseña no puede estar vacía.'),
        (N'en-US', N'Mensajes.Usuarios.PasswordRequerida', N'The password cannot be empty.'),
        (N'es-AR', N'Mensajes.Usuarios.SeleccionarUsuarioBlanquearPassword', N'Seleccioná un usuario de la grilla antes de blanquear su contraseña.'),
        (N'en-US', N'Mensajes.Usuarios.SeleccionarUsuarioBlanquearPassword', N'Select a user from the grid before resetting the password.'),
        (N'es-AR', N'Mensajes.Usuarios.SeleccionarUsuarioCambiarEstado', N'Seleccioná un usuario de la grilla antes de cambiar su estado.'),
        (N'en-US', N'Mensajes.Usuarios.SeleccionarUsuarioCambiarEstado', N'Select a user from the grid before changing the status.'),
        (N'es-AR', N'Mensajes.Usuarios.SeleccionarUsuarioEditar', N'Seleccioná un usuario de la grilla antes de editar.'),
        (N'en-US', N'Mensajes.Usuarios.SeleccionarUsuarioEditar', N'Select a user from the grid before editing.'),
        (N'es-AR', N'Mensajes.Usuarios.SeleccionarUsuarioHistorialEmail', N'Debe seleccionar un usuario para ver el historial de email.'),
        (N'en-US', N'Mensajes.Usuarios.SeleccionarUsuarioHistorialEmail', N'You must select a user to view the email history.'),
        (N'es-AR', N'Mensajes.Usuarios.ServicioGestionNoRecibido', N'El formulario no recibió el servicio de gestión de usuarios.'),
        (N'en-US', N'Mensajes.Usuarios.ServicioGestionNoRecibido', N'The form did not receive the user management service.'),
        (N'es-AR', N'Mensajes.Usuarios.UsuarioCreado', N'Usuario creado correctamente.'),
        (N'en-US', N'Mensajes.Usuarios.UsuarioCreado', N'User created successfully.'),
        (N'es-AR', N'Mensajes.Usuarios.UsuarioInhabilitado', N'Usuario inhabilitado correctamente.'),
        (N'en-US', N'Mensajes.Usuarios.UsuarioInhabilitado', N'User disabled successfully.'),
        (N'es-AR', N'Mensajes.Usuarios.UsuarioModificado', N'Usuario modificado correctamente.'),
        (N'en-US', N'Mensajes.Usuarios.UsuarioModificado', N'User updated successfully.'),
        (N'es-AR', N'Mensajes.Usuarios.UsuarioReactivado', N'Usuario reactivado correctamente.'),
        (N'en-US', N'Mensajes.Usuarios.UsuarioReactivado', N'User reactivated successfully.'),
        (N'es-AR', N'Permisos.Asignacion.Ayuda', N'Al marcar un rol, sus hijos se marcan visualmente en forma recursiva dentro del árbol Composite.'),
        (N'en-US', N'Permisos.Asignacion.Ayuda', N'When a role is selected, its children are visually selected recursively in the Composite tree.'),
        (N'es-AR', N'Permisos.Asignacion.GuardadoOk', N'Los permisos del usuario se guardaron correctamente.'),
        (N'en-US', N'Permisos.Asignacion.GuardadoOk', N'The user''s permissions were saved successfully.'),
        (N'es-AR', N'Permisos.Asignacion.PermisosDirectos', N'Permisos directos'),
        (N'en-US', N'Permisos.Asignacion.PermisosDirectos', N'Direct permissions'),
        (N'es-AR', N'Permisos.Asignacion.Roles', N'Roles'),
        (N'en-US', N'Permisos.Asignacion.Roles', N'Roles'),
        (N'es-AR', N'Permisos.Asignacion.Titulo', N'Asignación de permisos'),
        (N'en-US', N'Permisos.Asignacion.Titulo', N'Permission assignment'),
        (N'es-AR', N'Permisos.Asignacion.Usuario', N'Usuario: {0}'),
        (N'en-US', N'Permisos.Asignacion.Usuario', N'User: {0}'),
        (N'es-AR', N'Permisos.Componentes.Permiso', N'Permiso'),
        (N'en-US', N'Permisos.Componentes.Permiso', N'Permission'),
        (N'es-AR', N'Permisos.Componentes.Rol', N'Rol'),
        (N'en-US', N'Permisos.Componentes.Rol', N'Role'),
        (N'es-AR', N'Principal.Bienvenida', N'Bienvenido al sistema'),
        (N'en-US', N'Principal.Bienvenida', N'Welcome to the system'),
        (N'es-AR', N'Principal.CerrarSesion', N'Cerrar sesión'),
        (N'en-US', N'Principal.CerrarSesion', N'Sign out'),
        (N'es-AR', N'Principal.ConsultaBitacora', N'Bitácora'),
        (N'en-US', N'Principal.ConsultaBitacora', N'Audit log'),
        (N'es-AR', N'Principal.DesbloquearIntegridad', N'Desbloquear integridad'),
        (N'en-US', N'Principal.DesbloquearIntegridad', N'Unblock integrity'),
        (N'es-AR', N'Principal.Descripcion', N'La sesión fue iniciada correctamente. Este es el panel principal.'),
        (N'en-US', N'Principal.Descripcion', N'The session was started successfully. This is the main dashboard.'),
        (N'es-AR', N'Principal.GestionIdiomas', N'Idiomas'),
        (N'en-US', N'Principal.GestionIdiomas', N'Languages'),
        (N'es-AR', N'Principal.GestionRoles', N'Roles'),
        (N'en-US', N'Principal.GestionRoles', N'Roles'),
        (N'es-AR', N'Principal.GestionTraducciones', N'Traducciones'),
        (N'en-US', N'Principal.GestionTraducciones', N'Translations'),
        (N'es-AR', N'Principal.GestionUsuarios', N'Gestión de usuarios'),
        (N'en-US', N'Principal.GestionUsuarios', N'User management'),
        (N'es-AR', N'Principal.Idioma', N'Idioma'),
        (N'en-US', N'Principal.Idioma', N'Language'),
        (N'es-AR', N'Principal.Marca', N'BG'),
        (N'en-US', N'Principal.Marca', N'BG'),
        (N'es-AR', N'Principal.RecalcularDigitos', N'Recalcular DV'),
        (N'en-US', N'Principal.RecalcularDigitos', N'Recalculate verification digits'),
        (N'es-AR', N'Principal.ResumenTexto', N'Panel para acceder a los diferentes módulos del sistema a medida que los vayamos implementando.'),
        (N'en-US', N'Principal.ResumenTexto', N'Panel for accessing the different system modules as they are implemented.'),
        (N'es-AR', N'Principal.ResumenTitulo', N'Estado del sistema'),
        (N'en-US', N'Principal.ResumenTitulo', N'System status'),
        (N'es-AR', N'Principal.Salir', N'Salir'),
        (N'en-US', N'Principal.Salir', N'Exit'),
        (N'es-AR', N'Principal.Seccion', N'Navegación'),
        (N'en-US', N'Principal.Seccion', N'Navigation'),
        (N'es-AR', N'Principal.Subtitulo', N'Gestión principal del sistema'),
        (N'en-US', N'Principal.Subtitulo', N'Main system management'),
        (N'es-AR', N'Principal.Titulo', N'Panel principal'),
        (N'en-US', N'Principal.Titulo', N'Main dashboard'),
        (N'es-AR', N'Principal.TituloVentana', N'Panel principal'),
        (N'en-US', N'Principal.TituloVentana', N'Main dashboard'),
        (N'es-AR', N'Roles.Gestion.Activo', N'Activo'),
        (N'en-US', N'Roles.Gestion.Activo', N'Active'),
        (N'es-AR', N'Roles.Gestion.Ayuda', N'Seleccione un rol existente para administrar su composición o cree uno nuevo cargando sus atributos y marcando permisos o subroles en el árbol.'),
        (N'en-US', N'Roles.Gestion.Ayuda', N'Select an existing role to manage its composition, or create a new one by entering its attributes and selecting permissions or subroles in the tree.'),
        (N'es-AR', N'Roles.Gestion.Cancelar', N'Cancelar'),
        (N'en-US', N'Roles.Gestion.Cancelar', N'Cancel'),
        (N'es-AR', N'Roles.Gestion.Cerrar', N'Cerrar'),
        (N'en-US', N'Roles.Gestion.Cerrar', N'Close'),
        (N'es-AR', N'Roles.Gestion.Codigo', N'Código'),
        (N'en-US', N'Roles.Gestion.Codigo', N'Code'),
        (N'es-AR', N'Roles.Gestion.ConfirmarEliminar', N'¿Está seguro de eliminar el rol ''{0}''?' + NCHAR(13) + NCHAR(10) + N'' + NCHAR(13) + NCHAR(10) + N'También se eliminarán sus relaciones y asignaciones.'),
        (N'en-US', N'Roles.Gestion.ConfirmarEliminar', N'Are you sure you want to delete the role ''{0}''?' + NCHAR(13) + NCHAR(10) + N'' + NCHAR(13) + NCHAR(10) + N'Its relationships and assignments will also be deleted.'),
        (N'es-AR', N'Roles.Gestion.ConfirmarEliminarTitulo', N'Confirmar eliminación'),
        (N'en-US', N'Roles.Gestion.ConfirmarEliminarTitulo', N'Confirm deletion'),
        (N'es-AR', N'Roles.Gestion.CreadoOk', N'El rol se creó correctamente.'),
        (N'en-US', N'Roles.Gestion.CreadoOk', N'The role was created successfully.'),
        (N'es-AR', N'Roles.Gestion.CrearRol', N'Crear rol'),
        (N'en-US', N'Roles.Gestion.CrearRol', N'Create role'),
        (N'es-AR', N'Roles.Gestion.Descripcion', N'Descripción'),
        (N'en-US', N'Roles.Gestion.Descripcion', N'Description'),
        (N'es-AR', N'Roles.Gestion.EditarRol', N'Editar datos'),
        (N'en-US', N'Roles.Gestion.EditarRol', N'Edit details'),
        (N'es-AR', N'Roles.Gestion.EliminadoOk', N'El rol se eliminó correctamente.'),
        (N'en-US', N'Roles.Gestion.EliminadoOk', N'The role was deleted successfully.'),
        (N'es-AR', N'Roles.Gestion.EliminarRol', N'Eliminar rol'),
        (N'en-US', N'Roles.Gestion.EliminarRol', N'Delete role'),
        (N'es-AR', N'Roles.Gestion.GuardadoOk', N'La composición del rol se guardó correctamente.'),
        (N'en-US', N'Roles.Gestion.GuardadoOk', N'The role composition was saved successfully.'),
        (N'es-AR', N'Roles.Gestion.GuardarCambios', N'Guardar cambios'),
        (N'en-US', N'Roles.Gestion.GuardarCambios', N'Save changes'),
        (N'es-AR', N'Roles.Gestion.GuardarComposicion', N'Guardar composición'),
        (N'en-US', N'Roles.Gestion.GuardarComposicion', N'Save composition'),
        (N'es-AR', N'Roles.Gestion.ModificadoOk', N'Los datos del rol se modificaron correctamente.'),
        (N'en-US', N'Roles.Gestion.ModificadoOk', N'The role details were updated successfully.'),
        (N'es-AR', N'Roles.Gestion.Nombre', N'Nombre'),
        (N'en-US', N'Roles.Gestion.Nombre', N'Name'),
        (N'es-AR', N'Roles.Gestion.NuevoRol', N'Nuevo rol'),
        (N'en-US', N'Roles.Gestion.NuevoRol', N'New role'),
        (N'es-AR', N'Roles.Gestion.Permisos', N'Permisos directos'),
        (N'en-US', N'Roles.Gestion.Permisos', N'Direct permissions'),
        (N'es-AR', N'Roles.Gestion.RolActual', N' - rol actual'),
        (N'en-US', N'Roles.Gestion.RolActual', N' - current role'),
        (N'es-AR', N'Roles.Gestion.RolExistente', N'Rol existente'),
        (N'en-US', N'Roles.Gestion.RolExistente', N'Existing role'),
        (N'es-AR', N'Roles.Gestion.Roles', N'Roles y subroles'),
        (N'en-US', N'Roles.Gestion.Roles', N'Roles and subroles'),
        (N'es-AR', N'Roles.Gestion.Titulo', N'Gestión de roles'),
        (N'en-US', N'Roles.Gestion.Titulo', N'Role management'),
        (N'es-AR', N'Roles.Gestion.TituloVentana', N'Gestión de roles'),
        (N'en-US', N'Roles.Gestion.TituloVentana', N'Role management'),
        (N'es-AR', N'Traducciones.Cerrar', N'Cerrar'),
        (N'en-US', N'Traducciones.Cerrar', N'Close'),
        (N'es-AR', N'Traducciones.Clave', N'Clave'),
        (N'en-US', N'Traducciones.Clave', N'Key'),
        (N'es-AR', N'Traducciones.Eliminar', N'Eliminar'),
        (N'en-US', N'Traducciones.Eliminar', N'Delete'),
        (N'es-AR', N'Traducciones.Grilla.Clave', N'Clave'),
        (N'en-US', N'Traducciones.Grilla.Clave', N'Key'),
        (N'es-AR', N'Traducciones.Grilla.Texto', N'Texto'),
        (N'en-US', N'Traducciones.Grilla.Texto', N'Text'),
        (N'es-AR', N'Traducciones.Guardar', N'Guardar'),
        (N'en-US', N'Traducciones.Guardar', N'Save'),
        (N'es-AR', N'Traducciones.Idioma', N'Idioma'),
        (N'en-US', N'Traducciones.Idioma', N'Language'),
        (N'es-AR', N'Traducciones.Modificar', N'Modificar'),
        (N'en-US', N'Traducciones.Modificar', N'Edit'),
        (N'es-AR', N'Traducciones.Nuevo', N'Nuevo'),
        (N'en-US', N'Traducciones.Nuevo', N'New'),
        (N'es-AR', N'Traducciones.Texto', N'Texto'),
        (N'en-US', N'Traducciones.Texto', N'Text'),
        (N'es-AR', N'Traducciones.TituloVentana', N'Gestión de traducciones'),
        (N'en-US', N'Traducciones.TituloVentana', N'Translation management'),
        (N'es-AR', N'Usuarios.AccionesRapidas', N'Acciones rápidas'),
        (N'en-US', N'Usuarios.AccionesRapidas', N'Quick actions'),
        (N'es-AR', N'Usuarios.Cancelar', N'Cancelar'),
        (N'en-US', N'Usuarios.Cancelar', N'Cancel'),
        (N'es-AR', N'Usuarios.Cerrar', N'Cerrar'),
        (N'en-US', N'Usuarios.Cerrar', N'Close'),
        (N'es-AR', N'Usuarios.DatosUsuario', N'Edición de usuario'),
        (N'en-US', N'Usuarios.DatosUsuario', N'User details'),
        (N'es-AR', N'Usuarios.Editar', N'Editar'),
        (N'en-US', N'Usuarios.Editar', N'Edit'),
        (N'es-AR', N'Usuarios.Email', N'Email'),
        (N'en-US', N'Usuarios.Email', N'Email'),
        (N'es-AR', N'Usuarios.Estado', N'Estado'),
        (N'en-US', N'Usuarios.Estado', N'Status'),
        (N'es-AR', N'Usuarios.Estado.Activo', N'Activo'),
        (N'en-US', N'Usuarios.Estado.Activo', N'Active'),
        (N'es-AR', N'Usuarios.Estado.Inactivo', N'Inactivo'),
        (N'en-US', N'Usuarios.Estado.Inactivo', N'Inactive'),
        (N'es-AR', N'Usuarios.FechaCreacion', N'Fecha creación'),
        (N'en-US', N'Usuarios.FechaCreacion', N'Creation date'),
        (N'es-AR', N'Usuarios.Grilla.Email', N'Email'),
        (N'en-US', N'Usuarios.Grilla.Email', N'Email'),
        (N'es-AR', N'Usuarios.Grilla.Estado', N'Estado'),
        (N'en-US', N'Usuarios.Grilla.Estado', N'Status'),
        (N'es-AR', N'Usuarios.Grilla.FechaCreacion', N'Fecha creación'),
        (N'en-US', N'Usuarios.Grilla.FechaCreacion', N'Creation date'),
        (N'es-AR', N'Usuarios.Grilla.NombreCompleto', N'Nombre completo'),
        (N'en-US', N'Usuarios.Grilla.NombreCompleto', N'Full name'),
        (N'es-AR', N'Usuarios.Grilla.UltimoAcceso', N'Último acceso'),
        (N'en-US', N'Usuarios.Grilla.UltimoAcceso', N'Last access'),
        (N'es-AR', N'Usuarios.Grilla.Usuario', N'Usuario'),
        (N'en-US', N'Usuarios.Grilla.Usuario', N'Username'),
        (N'es-AR', N'Usuarios.Guardar', N'Guardar'),
        (N'en-US', N'Usuarios.Guardar', N'Save'),
        (N'es-AR', N'Usuarios.HistorialEmail', N'Historial email'),
        (N'en-US', N'Usuarios.HistorialEmail', N'Email history'),
        (N'es-AR', N'Usuarios.Id', N'Id'),
        (N'en-US', N'Usuarios.Id', N'Id'),
        (N'es-AR', N'Usuarios.Inhabilitar', N'Inhabilitar'),
        (N'en-US', N'Usuarios.Inhabilitar', N'Disable'),
        (N'es-AR', N'Usuarios.InhabilitarReactivar', N'Inhabilitar/Reactivar'),
        (N'en-US', N'Usuarios.InhabilitarReactivar', N'Disable/Reactivate'),
        (N'es-AR', N'Usuarios.NombreCompleto', N'Nombre completo'),
        (N'en-US', N'Usuarios.NombreCompleto', N'Full name'),
        (N'es-AR', N'Usuarios.NombreUsuario', N'Nombre de usuario'),
        (N'en-US', N'Usuarios.NombreUsuario', N'Username'),
        (N'es-AR', N'Usuarios.NuevaPassword', N'Nueva contraseña'),
        (N'en-US', N'Usuarios.NuevaPassword', N'New password'),
        (N'es-AR', N'Usuarios.Nuevo', N'Nuevo'),
        (N'en-US', N'Usuarios.Nuevo', N'New'),
        (N'es-AR', N'Usuarios.Permisos', N'Permisos'),
        (N'en-US', N'Usuarios.Permisos', N'Permissions'),
        (N'es-AR', N'Usuarios.Reactivar', N'Reactivar'),
        (N'en-US', N'Usuarios.Reactivar', N'Reactivate'),
        (N'es-AR', N'Usuarios.RestablecerPassword', N'Restablecer contraseña'),
        (N'en-US', N'Usuarios.RestablecerPassword', N'Reset password'),
        (N'es-AR', N'Usuarios.Subtitulo', N'Administración de usuarios del sistema'),
        (N'en-US', N'Usuarios.Subtitulo', N'System user administration'),
        (N'es-AR', N'Usuarios.Titulo', N'Gestión de Usuarios'),
        (N'en-US', N'Usuarios.Titulo', N'User Management'),
        (N'es-AR', N'Usuarios.TituloVentana', N'Gestión de Usuarios'),
        (N'en-US', N'Usuarios.TituloVentana', N'User Management'),
        (N'es-AR', N'Usuarios.UltimoAcceso', N'Último acceso'),
        (N'en-US', N'Usuarios.UltimoAcceso', N'Last access');

    UPDATE destino
    SET destino.Texto = origen.Texto
    FROM dbo.Traduccion AS destino
    INNER JOIN dbo.Idioma AS idioma
        ON idioma.Id = destino.IdiomaId
    INNER JOIN @Traducciones AS origen
        ON origen.CodigoIdioma = idioma.Codigo
       AND origen.Clave = destino.Clave
    WHERE destino.Texto <> origen.Texto;

    INSERT INTO dbo.Traduccion (Id, Clave, IdiomaId, Texto)
    SELECT
        NEWID(),
        origen.Clave,
        idioma.Id,
        origen.Texto
    FROM @Traducciones AS origen
    INNER JOIN dbo.Idioma AS idioma
        ON idioma.Codigo = origen.CodigoIdioma
    WHERE NOT EXISTS
    (
        SELECT 1
        FROM dbo.Traduccion AS existente
        WHERE existente.IdiomaId = idioma.Id
          AND existente.Clave = origen.Clave
    );

    COMMIT TRANSACTION;

    SELECT
        idioma.Codigo AS CodigoIdioma,
        COUNT(*) AS CantidadTraducciones
    FROM dbo.Traduccion AS traduccion
    INNER JOIN dbo.Idioma AS idioma
        ON idioma.Id = traduccion.IdiomaId
    WHERE idioma.Codigo IN (N'es-AR', N'en-US')
    GROUP BY idioma.Codigo
    ORDER BY idioma.Codigo;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    THROW;
END CATCH;
GO

-- Verificación opcional: claves faltantes entre ambos idiomas.
WITH Claves AS
(
    SELECT DISTINCT Clave
    FROM dbo.Traduccion
)
SELECT
    claves.Clave,
    MAX(CASE WHEN idioma.Codigo = N'es-AR' THEN 1 ELSE 0 END) AS TieneEspanol,
    MAX(CASE WHEN idioma.Codigo = N'en-US' THEN 1 ELSE 0 END) AS TieneIngles
FROM Claves AS claves
LEFT JOIN dbo.Traduccion AS traduccion
    ON traduccion.Clave = claves.Clave
LEFT JOIN dbo.Idioma AS idioma
    ON idioma.Id = traduccion.IdiomaId
   AND idioma.Codigo IN (N'es-AR', N'en-US')
GROUP BY claves.Clave
HAVING
    MAX(CASE WHEN idioma.Codigo = N'es-AR' THEN 1 ELSE 0 END) = 0
    OR MAX(CASE WHEN idioma.Codigo = N'en-US' THEN 1 ELSE 0 END) = 0;
GO